In [1]:
import numpy as np

In [3]:
a=np.random.randint(0,10, size=(3,6))

tek bir değişken tipinde değerler tutabilir

In [4]:
a

array([[7, 8, 9, 2, 5, 2],
       [8, 8, 2, 6, 2, 6],
       [5, 2, 5, 2, 3, 2]])

In [5]:
print("boyutu" , a.ndim)

boyutu 2


In [6]:
print("şekli" , a.shape)

şekli (3, 6)


In [7]:
print("eleman sayısı" , a.size)

eleman sayısı 18


In [8]:
print("değişken tipi" , a.dtype)

değişken tipi int32


In [9]:
a.reshape((9,2))

array([[7, 8],
       [9, 2],
       [5, 2],
       [8, 8],
       [2, 6],
       [2, 6],
       [5, 2],
       [5, 2],
       [3, 2]])

reshape ile satır sütun sayısını değiştirebiliriz


In [10]:
a.reshape((1,18))

array([[7, 8, 9, 2, 5, 2, 8, 8, 2, 6, 2, 6, 5, 2, 5, 2, 3, 2]])

In [12]:
a=np.array([[1,2,3],[4,5,6]])

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b=np.array([[20,30,40],[50,60,70]])

In [15]:
b

array([[20, 30, 40],
       [50, 60, 70]])

concatenate iki matrisi birbirine yapıştırır

In [19]:
np.concatenate([a,b]) #dikey birleştirme

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [20, 30, 40],
       [50, 60, 70]])

In [18]:
np.concatenate([a,b] , axis=1) #yatay birleştirme

array([[ 1,  2,  3, 20, 30, 40],
       [ 4,  5,  6, 50, 60, 70]])

In [21]:
a=np.array([2,1,4,99,29,3,51])
b=np.sort(a)
b

array([ 1,  2,  3,  4, 29, 51, 99])

In [26]:
b[::-1]

array([99, 51, 29,  4,  3,  2,  1])

In [29]:
x=np.full((4,3),7)
x

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [31]:
x.T #transpoz alma

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])