# Index ile Elemanlara Erişmek


In [1]:
import numpy as np

In [3]:
a=np.random.randint(10 , size=10)
a

array([4, 8, 3, 7, 3, 4, 6, 2, 1, 7])

In [8]:
a[3]

7

In [5]:
m=np.random.randint(10 , size=(3,5))
m

array([[0, 2, 6, 0, 0],
       [9, 9, 4, 5, 0],
       [6, 6, 1, 3, 3]])

In [7]:
m[1,0]

9

# Array Alt Küme İşlemleri


In [9]:
import numpy as np

In [11]:
b=np.arange(2,30)
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
b[0:3] # 0'dan 3e kadar olan indesler

array([2, 3, 4])

In [13]:
b[5:] #belli bir indesten sona kadar

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29])

In [14]:
b[1::2] # 1. elemandan başlayarak 2'şer 2'şer artacak şekilde

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## iki boyutlu slice

In [16]:
n=np.random.randint(10 , size = [5,5])
n

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 8, 4],
       [9, 8, 7, 1, 1],
       [3, 4, 1, 2, 1],
       [1, 0, 5, 8, 1]])

In [19]:
n[:2] # 0'dan 2. satıra

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 8, 4]])

In [20]:
n[3:] # 3 sütundan sona kadar

array([[3, 4, 1, 2, 1],
       [1, 0, 5, 8, 1]])

In [22]:
n[1,:] # 1.satırda tüm sütunlar

array([0, 1, 7, 8, 4])

In [23]:
n[0:2 , 1:3] # satırda 0dan 2 ye kadar ve sütunda 1den 3e kadar al

array([[3, 3],
       [1, 7]])

In [27]:
n[:: , :2] # bütün satırları ve 0dan 3 sütunları al

array([[1, 3],
       [0, 1],
       [9, 8],
       [3, 4],
       [1, 0]])

In [28]:
n[: , :2] # bütün satırları ve 0dan 3 sütunları al ## tek : ile de oluyor

array([[1, 3],
       [0, 1],
       [9, 8],
       [3, 4],
       [1, 0]])

In [31]:
n[1:3 , 0:3]

array([[0, 1, 7],
       [9, 8, 7]])