# Koşullu Eleman İşlemleri


In [2]:
import numpy as np
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [3]:
v>5

array([False, False, False, False, False])

In [14]:
v<3

array([ True,  True, False, False, False])

In [16]:
v[v<=3]

array([1, 2, 3])

In [17]:
v[v !=3]

array([1, 2, 4, 5])

In [18]:
v*2

array([ 2,  4,  6,  8, 10])

In [19]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [4]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

# Matematiksel İşlemler

In [5]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
#ufunc

In [11]:
np.subtract(a,1) #çıkarma

array([0, 1, 2, 3, 4])

In [12]:
np.add(v,1) #ekleme

array([2, 3, 4, 5, 6])

In [13]:
np.multiply(v,2) #çarpma

array([ 2,  4,  6,  8, 10])

In [16]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [17]:
np.power(v,3) #üst alma

array([  1,   8,  27,  64, 125], dtype=int32)

In [19]:
np.mod(v,2) #2ye bölümden kalan

array([1, 0, 1, 0, 1], dtype=int32)

In [20]:
np.absolute(np.array([-3])) #mutlak değer almak için

array([3])

In [21]:
np.sin(360)

0.9589157234143065

In [23]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [24]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [25]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\acer\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\acer\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [26]:
#cheatsheet kopya kağıdı demek (googleda aratırken)

# Numpy ile İki Bilinmeyenli Denklem Çözümü

In [27]:
import numpy as np

5*x0+x1=12

x0+3*x1=10

In [30]:
a=np.array([[5,1] , [1,3] ])
a

array([[5, 1],
       [1, 3]])

In [32]:
b=np.array([12,10])
b

array([12, 10])

In [33]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])