In [1]:
import numpy as np

np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [13]:
v=np.array=([1,8,3,4,5])
np.sort(v)

array([1, 3, 4, 5, 8])

In [8]:
a=np.array=([4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2])
a

([4, 7, 4, 5, 9], [2, 5, 0, 7, 7], [1, 9, 0, 8, 2])

In [9]:
a[2,3]

TypeError: tuple indices must be integers or slices, not tuple

In [10]:
5*np.array([1,2,3])

TypeError: 'tuple' object is not callable

In [11]:
import numpy as np

h = np.array([2, 1, 4, 3, 5])

np.sort(h)

TypeError: 'tuple' object is not callable

In [14]:
array([  
[[7, 9],[4, 0],[5, 9]],

[
[4, 8],
[6, 4],
[4, 5]
],

[
[2, 2],
[8, 2],
[0, 2] 
]
])

NameError: name 'array' is not defined

In [15]:


import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:

a[0:1]

([4, 7, 4, 5, 9],)

In [19]:
import numpy as np
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
m=np.array=([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

In [23]:
m[0,[1,2]]

TypeError: list indices must be integers or slices, not tuple

In [26]:
import numpy as np
k=np.array([[[7, 9],[4, 0],[5, 9]],[[4, 8],[6, 4],[4, 5]],[[2, 2],[8, 2],[0, 2]]])

TypeError: 'list' object is not callable

In [29]:
import numpy as np

t=np.array([3.14, 4 ,6 ,1.2])
t

TypeError: 'list' object is not callable

TypeError: 'list' object is not callable