# concatenate (birleştirme)

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [5]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [4]:
np.concatenate([[x],[y]])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a=np.array([[1,2,3] ,[4,5,6]])

In [10]:
np.concatenate([a,a]) #birleştirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [11]:
np.concatenate([a,a] , axis=0) #x=0 satır bazında birleştirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
np.concatenate([a,a] , axis=1) #y=1 sütün bazında birleştirme

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])