In [2]:
import numpy as np

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a=np.arange(1,10) #tek köşeli parantez var

In [8]:
b=a.reshape((1,9))

In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [13]:
b #iki köşeli parantez var

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])