# Alt Küme Üzerinde İşlem Yapmak
## COPY FONK


In [2]:
import numpy as np

In [4]:
a=np.random.randint(10, size=(5,5))
a

array([[7, 2, 6, 1, 9],
       [9, 8, 4, 3, 2],
       [1, 5, 0, 4, 6],
       [7, 8, 9, 8, 8],
       [5, 0, 5, 0, 2]])

In [6]:
alt_a= a[0:3 , 0:2]
alt_a

array([[7, 2],
       [9, 8],
       [1, 5]])

In [8]:
alt_a[0,0]=9999
alt_a[1,1]=75

In [9]:
a # a üzerinde değişiklik yaptı

array([[9999,    2,    6,    1,    9],
       [   9,   75,    4,    3,    2],
       [   1,    5,    0,    4,    6],
       [   7,    8,    9,    8,    8],
       [   5,    0,    5,    0,    2]])

In [11]:
alt_a # alt_a oluşurken kırpıldı 

array([[9999,    2],
       [   9,   75],
       [   1,    5]])

In [12]:
b=np.random.randint(10, size=(5,5))
b

array([[8, 1, 6, 3, 3],
       [7, 1, 8, 0, 6],
       [0, 9, 1, 5, 0],
       [5, 4, 8, 9, 6],
       [9, 0, 4, 7, 7]])

In [24]:
alt_b=b[0:3 , 0:2].copy() #copy fonksiyonu
alt_b

array([[8, 1],
       [7, 1],
       [0, 9]])

In [25]:
alt_b[0,0]=9999
alt_b[1,1]=85

In [26]:
alt_b

array([[9999,    1],
       [   7,   85],
       [   0,    9]])

In [21]:
b

array([[8, 1, 6, 3, 3],
       [7, 1, 8, 0, 6],
       [0, 9, 1, 5, 0],
       [5, 4, 8, 9, 6],
       [9, 0, 4, 7, 7]])

In [27]:
alt_b+3

array([[10002,     4],
       [   10,    88],
       [    3,    12]])

In [28]:
b # copy fonk ile yazıldığında b'den bağımsız oldu

array([[8, 1, 6, 3, 3],
       [7, 1, 8, 0, 6],
       [0, 9, 1, 5, 0],
       [5, 4, 8, 9, 6],
       [9, 0, 4, 7, 7]])