# sorting (sıralama)

In [1]:
import numpy as np

In [3]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [18]:
 v.sort()

In [19]:
v

array([1, 2, 3, 4, 5])

## iki boyutlu array sıralama

In [21]:
m=np.random.normal(20,5 , [3,3])
m

array([[20.21404346, 15.02825463, 12.95418348],
       [24.93882022, 18.43216023, 19.59702365],
       [11.08185155, 24.0030337 , 26.89938417]])

In [24]:
np.sort(m, axis=0) #satıra göre sıralama

array([[11.08185155, 15.02825463, 12.95418348],
       [20.21404346, 18.43216023, 19.59702365],
       [24.93882022, 24.0030337 , 26.89938417]])

In [25]:
np.sort(m, axis=1) #sütuna göre sıralama

array([[12.95418348, 15.02825463, 20.21404346],
       [18.43216023, 19.59702365, 24.93882022],
       [11.08185155, 24.0030337 , 26.89938417]])