# splitting (array ayırma)

In [1]:
import numpy as np

In [5]:
x=np.array([1,2,3,99,99,3,2,1])

In [7]:
np.split(x, [3,5,6])

[array([1, 2, 3]), array([99, 99]), array([3]), array([2, 1])]

3'e kadar 5'e kadar ve 6'ya kadar ayırma yapma

In [8]:
a,b,c,d=np.split(x, [3,5,6])

In [9]:
a

array([1, 2, 3])

In [10]:
print(a , b, c, d)

[1 2 3] [99 99] [3] [2 1]


iki boyutlu ayırma

In [12]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.vsplit(m,[2,3]) # 2. elemandan ve 3. elemandan böl

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [17]:
ust,alt=np.vsplit(m,[2]) # 2. elemandan böl ve ikiye ayır

In [22]:
print("ust--> " ,ust)
print("alt--> " ,alt)

ust-->  [[0 1 2 3]
 [4 5 6 7]]
alt-->  [[ 8  9 10 11]
 [12 13 14 15]]


In [23]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.hsplit(m , [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [26]:
sol,sag=np.hsplit(m, [2])

In [28]:
print("sol--> " ,sol)
print("sag--> " ,sag)

sol--> /n  [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
sag-->  [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
