# Fancy Index ile Elemanlara Erişmek

In [1]:
import numpy as np
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
v[1]

3

In [3]:
v[5]

15

In [4]:
v[9]

27

In [5]:
al_getir=[1,5,9]

In [6]:
v[al_getir]

array([ 3, 15, 27])

In [7]:
#basit index ile fancy index


In [8]:
n=np.random.randint(10 , size = [5,5])
n

array([[0, 0, 5, 1, 7],
       [5, 6, 7, 0, 2],
       [8, 9, 0, 7, 9],
       [5, 4, 2, 4, 5],
       [8, 2, 8, 0, 3]])

In [9]:
n[0, [1,2]]

array([0, 5])

In [10]:
#slice ile fancy
n[0: , [1,2]]

array([[0, 5],
       [6, 7],
       [9, 0],
       [4, 2],
       [2, 8]])

In [12]:
import numpy as np
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [13]:
v>5

array([False, False, False, False, False])

In [14]:
v<3

array([ True,  True, False, False, False])

In [16]:
v[v<=3]

array([1, 2, 3])

In [17]:
v[v !=3]

array([1, 2, 4, 5])

In [18]:
v*2

array([ 2,  4,  6,  8, 10])

In [19]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [21]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)