ndim:  _boyut sayısı_

shape:  _boyut bilgisi_

size:  _toplam eleman sayısı_

dtype: _array veri tipi_

In [1]:
import numpy as np

In [2]:
np.random.randint(10 , size=10)

array([8, 2, 1, 6, 6, 2, 5, 4, 0, 1])

In [3]:
a=np.random.randint(10 , size=10)

In [4]:
a.ndim

1

In [5]:
a.shape

(10,)

In [6]:
a.size

10

In [7]:
a.dtype

dtype('int32')

In [11]:
b=np.random.randint(10 , size=(3,5))

In [12]:
b

array([[1, 0, 4, 5, 7],
       [6, 7, 8, 0, 5],
       [2, 9, 8, 5, 4]])

In [13]:
b.ndim #boyut sayısı

2

In [14]:
b.shape #boyut bilgisi

(3, 5)

In [15]:
b.size

15

In [17]:
b.dtype

dtype('int32')

In [1]:
import numpy as np
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])